# Generated by Django 2.0.2 on 2018-05-17 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20180517_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='root',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='root_comment', to='comment.Comment'),
        ),
    ]
