# Generated by Django 2.0.2 on 2018-06-18 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_auto_20180618_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcommentcount',
            name='count',
            field=models.IntegerField(default=0, editable=False, verbose_name='新评论数'),
        ),
        migrations.AlterField(
            model_name='newcommentcount',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
    ]
