# Generated by Django 2.0.2 on 2018-06-18 16:41

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0013_auto_20180618_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='评论内容'),
        ),
    ]
