# Generated by Django 2.0.2 on 2018-06-23 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPSaver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='127.0.0.1', max_length=16)),
                ('blog_id', models.IntegerField(default=-1)),
                ('visited_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '访问IP',
                'verbose_name_plural': '访问IP',
            },
        ),
    ]
