# Generated by Django 2.0.2 on 2018-06-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipsaver',
            name='visited_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
