# Generated by Django 2.0.2 on 2018-06-23 00:01

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180618_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='博客内容'),
        ),
    ]
