# Generated by Django 2.0.2 on 2018-06-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0003_auto_20180618_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readdetail',
            options={'verbose_name': '日期阅读数', 'verbose_name_plural': '日期阅读数'},
        ),
        migrations.AlterModelOptions(
            name='readnum',
            options={'verbose_name': '阅读总数', 'verbose_name_plural': '阅读总数'},
        ),
    ]
